version: '3.8'

services:
  percona-db:
    image: percona/percona-server:8.0
    cap_add:
      - SYS_NICE
    container_name: percona-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NNPRO
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - nnpro_data:/var/lib/mysql

volumes:
  nnpro_data: